version: "2"
services:
   namenode:
      image: eecs4415/hadoop
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode:
      image: eecs4415/hadoop
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
   datanode2:
      image: eecs4415/hadoop
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
   resourcemanager:
      image: eecs4415/hadoop
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
      volumes:
        - ./test.sh:/opt/test.sh
        - ./data:/data
   nodemanager:
      image: eecs4415/hadoop
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
